# Base JRE image
FROM eclipse-temurin:21-jre
RUN apt-get update && apt-get install -y unzip && rm -rf /var/lib/apt/lists/*
WORKDIR /app

COPY ./gatasServer-shadow-*.zip /tmp

RUN unzip /tmp/gatasServer-shadow-*.zip -d /tmp/extract \
    && mv /tmp/extract/*/* /app/ \
    && rm -rf /tmp/extract /tmp/gatasServer-shadow-*.zip

RUN chmod +x /app/bin/*

CMD ["./bin/gatasServer"]
